[package]
name = "picosh"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.41", features = ["derive"] }
elf = "0.8.0"
serialport = "4.7.2"
# capstone = "0.11"
# object = "0.30"
# petgraph = "0.6"
# dotenv = "0.15"
# goblin = "0.10.0"
